services:
  latex:
    build: .
    container_name: my_latex_project
    volumes:
      - .:/workdir
    working_dir: /workdir
    # Biên dịch và symlink file pdf ra ngoài root thư mục để dễ theo dõi
    command: >
      sh -c "latexmk -pdf -pvc -shell-escape -interaction=nonstopmode -outdir=build main.tex && ln -sf build/main.pdf main.pdf"
    # Đảm bảo file PDF tạo ra thuộc quyền sở hữu của bạn (Ubuntu)
    user: "${UID:-1000}:${GID:-1000}"
